### ISSUE TITLE
Crashes when combined with Geyser Cracking (since new update)

### ISSUE THREAD

**Issue by Chobitaz** [Sgt-Imalas/Sgt_Imalas-Oni-Mods#10]
Since the latest update this mod crashes the game when combined with Geyser Cracking mod. If unchecked everything works again.

ArgumentNullException: Value cannot be null.
Parameter name: first

System.Linq.Enumerable.Intersect[TSource] (System.Collections.Generic.IEnumerable`1[T] first, System.Collections.Generic.IEnumerable`1[T] second) (at <351e49e2a5bf4fd6beabb458ce2255f3>:0)
Rockets_TinyYetBig.Patches+KGToUnitsPatch.Prefix (Storage __instance, System.Single& __result) (at <1601b5f7e1874295a2bd0f842e64e0b2>:0)
(wrapper dynamic-method) Storage.Storage.MassStored_Patch1(Storage)
HexiGeyserCracking.Crackable.Sim1000ms (System.Single dt) (at <12f18162d7224b06acaa36b7a9ec96f8>:0)
SimAndRenderScheduler+Sim1000msUpdater.Update (ISim1000ms updater, System.Single dt) (at <8c239b169b544cce8b8bc7ddd2d09e10>:0)
UpdateBucketWithUpdater`1[DataType].Update (System.Single dt) (at <8c239b169b544cce8b8bc7ddd2d09e10>:0)
StateMachineUpdater+BucketGroup.AdvanceOneSubTick (System.Single dt) (at <8c239b169b544cce8b8bc7ddd2d09e10>:0)
StateMachineUpdater.AdvanceOneSimSubTick () (at <8c239b169b544cce8b8bc7ddd2d09e10>:0)
Game.SimEveryTick (System.Single dt) (at <1c7e9ccb4aa844e2be4538990aabf98e>:0)
Game.Update () (at <1c7e9ccb4aa844e2be4538990aabf98e>:0)

Build: U42-514967-S

**Comment by Sgt-Imalas** [comment]
This crash (and the one with always show capacity) is a result of improper storage implementation at geyser cracking (no filter set). The mod assumed that atleast one filter was set, resulting in a nullpointerexception.

fixed in ver. 2.1
