### ISSUE TITLE
[BUG][VISUAL]: Tiny and Small Critters have a problem with sticking to surfaces

### ISSUE THREAD

**Issue by SakuraMajiKoi** [Sgt-Imalas/Sgt_Imalas-Oni-Mods#101]
### Which Mod?

Critter Traits

### Description of the bug/crash

I noticed that at least a pip and pipsqueak with the tiny and small traits floated when walking on walls and ceilings. There is no visual issue with walking on floors. Notably when changing from floor to wall, the sprite jumps to the misaligned position. 
Just in case my extensive mod list: 
https://pastebin.com/sx13RYmm though no 'critter' nor 'pip' mod should affect them

Screenshots:
Tiny Pipsqueak 
![20240310083026_1](https://github.com/Sgt-Imalas/Sgt_Imalas-Oni-Mods/assets/105113582/c5dd82ff-3bac-429f-8241-7570cff50e27)
![20240310083041_1](https://github.com/Sgt-Imalas/Sgt_Imalas-Oni-Mods/assets/105113582/d8b7d068-c209-4be7-83a5-318a9b56e46b)

Small adults floats a little:
![20240310083010_1](https://github.com/Sgt-Imalas/Sgt_Imalas-Oni-Mods/assets/105113582/e583812e-ef39-4ece-8c05-03c7a91b4958)

Normal sized adult is fine:
![20240310083333_1](https://github.com/Sgt-Imalas/Sgt_Imalas-Oni-Mods/assets/105113582/96375b62-ce13-40c7-baf1-cff1120ce695)

### Steps To Reproduce

Step 1: Have a critter that is able to walk on walls and ceilings with the trait 'Tiny' or 'Small' (applies to Pips at the very least, may also apply to bigger sizes and other critters)
Step 2: Have them walk on walls and ceilings.
Step 3: They stick out like a tiny sore thumb.

### Player.log

[Player.log](https://github.com/Sgt-Imalas/Sgt_Imalas-Oni-Mods/files/14549292/Player.log)

**Comment by Sgt-Imalas** [comment]
that bug was present in the original mod and the limits of the animation system don't allow fixing it
