### ISSUE TITLE
[BUG]: [crush] AI Controlled Rockets (DLC)

### ISSUE THREAD

**Issue by kuozhijishou** [Sgt-Imalas/Sgt_Imalas-Oni-Mods#102]
### Which Mod?

[crush] AI Controlled Rockets (DLC)

### Description of the bug/crash

[crush] AI Controlled Rockets (DLC)

### Steps To Reproduce

[crush] AI Controlled Rockets (DLC)

### Player.log
[Player.log](https://github.com/Sgt-Imalas/Sgt_Imalas-Oni-Mods/files/14627484/Player.log)

**Comment by Sgt-Imalas** [comment]
something in the spacemap is broken, not mod related
