### ISSUE TITLE
[BUG]: Better Rebuilding seems to crash frequently when used with Custom Reservoirs

### ISSUE THREAD

**Issue by neavo** [Sgt-Imalas/Sgt_Imalas-Oni-Mods#104]
### Which Mod?

Better Rebuilding

### Description of the bug/crash

When rebuilding the custom building Wall Gas Reservoir in the [Custom Reservoirs Mod](https://steamcommunity.com/sharedfiles/filedetails/?id=2407398520), there is a chance that the program will crash.

### Steps To Reproduce

as described above

### Player.log

[Player.log](https://github.com/Sgt-Imalas/Sgt_Imalas-Oni-Mods/files/14807197/Player.log)

**Comment by Sgt-Imalas** [comment]
in that log "fluid shipping" crashes, not custom reservoirs

**Comment by Sgt-Imalas** [comment]
added some extra cleanup with 1.1.1 that might mitigate this, however the crashing method has to be adjusted in fluid shipping
