### ISSUE TITLE
[BUG]: Debug Buttons unpauses game when disabling

### ISSUE THREAD

**Issue by andr9528** [Sgt-Imalas/Sgt_Imalas-Oni-Mods#105]
### Which Mod?

Debug Buttons

### Description of the bug/crash

When the debug botton is enabled, while the game is paused, and the debug button is then disabled, the game will run at what appears to be 1x speed.

I created a Gif of it happening, but it was too big to send to you on Discord. Let me know if you want it.

Not sure if it is a caused by a combination of my mods.
I do not have the debug file in the folder, as that would render the mod useless.

Acordding to the mod_info file it am currently running version 1.0.1.0.

### Steps To Reproduce

- Enable Debug
- Pause Game
- Disable Debug

### Player.log

[Player.log](https://github.com/Sgt-Imalas/Sgt_Imalas-Oni-Mods/files/14982959/Player.log)

**Comment by Sgt-Imalas** [comment]
fixed in release 1.0.2
