### ISSUE TITLE
[BUG]: Block not treated as Ground

### ISSUE THREAD

**Issue by TheGrey01** [Sgt-Imalas/Sgt_Imalas-Oni-Mods#109]
### Which Mod?

Utility Glass

### Description of the bug/crash

It's not a crash, but when you try to use this glass as a floor objects built on top of it don't recognize it as a valid location/tile.

### Steps To Reproduce

lay down some of these tiles and try to build structures on top, they show as invalid locations, although dupes WILL build them. they are not usable while on top of these tiles.

### Player.log

NA-Not a crash issue.

**Comment by Sgt-Imalas** [comment]
liquid pumps do not require floor, your issue is somewhere else.
also not reproducable
![grafik](https://github.com/Sgt-Imalas/Sgt_Imalas-Oni-Mods/assets/20609939/afd5d840-4efb-4a79-a8ff-4ad0235bd935)

**Comment by TheGrey01** [comment]
Not the pump it was the water drop off, not sure why it's giving me an issue since I see it's visually fine for you.
