### ISSUE TITLE
[Synchronize Mods] Game crash on start base game

### ISSUE THREAD

**Issue by konny87** [Sgt-Imalas/Sgt_Imalas-Oni-Mods#11]
Hey SGT_Imalas, my Game crashed on starting the base Game. I disabled all other Mods and the german language. 

Mod Version 2.0.2.0
[Player.log](https://github.com/Sgt-Imalas/Sgt_Imalas-Oni-Mods/files/9491318/Player.log)

Thanks and Kind regards
Konny87

**Comment by Sgt-Imalas** [comment]
Fixed in 2.1
