### ISSUE TITLE
[BUG]: Crash on Game Load

### ISSUE THREAD

**Issue by qops1981** [Sgt-Imalas/Sgt_Imalas-Oni-Mods#110]
### Which Mod?

Duplicant Stat Selector

### Description of the bug/crash

On Game load it immediately crashes and auto disables the Mod and subsequent game load 

### Steps To Reproduce

Have mod enabled and attempt to load/start the game

### Player.log

[Player.log](https://github.com/Sgt-Imalas/Sgt_Imalas-Oni-Mods/files/15382472/Player.log)

**Comment by Sgt-Imalas** [comment]
Get mod updater and let it update your mod, it is severely outdated (latest version is 6.2.4, you have 5.3 installed)
