### ISSUE TITLE
[BUG]: crash while saving stat changes

### ISSUE THREAD

**Issue by kstathem** [Sgt-Imalas/Sgt_Imalas-Oni-Mods#111]
### Which Mod?

Duplicant Stat Selector [DSS]

### Description of the bug/crash

The game crashes to desktop when I try to use the new feature to change a dupe's stats (specifically, to undo the effect of Stats Unlimited mod)
I am on Linux, have not tried on Windows to rule that out
I did try on a new save, it did not crash

### Steps To Reproduce

go to mod options, enable "Duplicity-style" editor
load the included save file
click on a duplicant, click on the new gear icon
click save changes (with or without changing anything)

### Player.log

[Player.log](https://github.com/Sgt-Imalas/Sgt_Imalas-Oni-Mods/files/15461418/Player.log)
[The Sneezing Rat's Nest.sav.zip](https://github.com/Sgt-Imalas/Sgt_Imalas-Oni-Mods/files/15461527/The.Sneezing.Rat.s.Nest.sav.zip)

**Comment by Sgt-Imalas** [comment]
thx for the report.
the crash is related to a bug in the mod code interacting with an active somnium synthesizer effect.
will fix soon

**Comment by Sgt-Imalas** [comment]
should be fixed in 7.0.2
