### ISSUE TITLE
[BUG]: Crash when pressing "Create New Preset" button

### ISSUE THREAD

**Issue by Glampi42** [Sgt-Imalas/Sgt_Imalas-Oni-Mods#114]
### Which Mod?

Mod Preset Manager [MPM]

### Description of the bug/crash

The game crashes when trying to create a new preset by pressing the "create" button.

### Steps To Reproduce

1. Launch the game
2. Press "Presets" button next to the "Mods" button
3. Press "Create New Preset" button at the bottom of the MPM's menu

### Player.log

[Player.log](https://github.com/user-attachments/files/16173159/Player.log)

**Comment by Sgt-Imalas** [comment]
thx for the report.
should be fixed with release 1.1.1
