### ISSUE TITLE
[BUG]: Crash Starting New Game with less than 3 duplicants (Survival - New Frosty Planet DLC)

### ISSUE THREAD

**Issue by Zibbibbo** [Sgt-Imalas/Sgt_Imalas-Oni-Mods#118]
### Which Mod?

Duplicant Stat Selector

### Description of the bug/crash

Starting a new game with 1 or 2 duplicants the game crash at first selection.
The problem is not present if i start with default 3 or more starting duplicants (with 4 duplicants it works).

### Steps To Reproduce

Set only 1 or 2 starting duplicant in the mod options

Start new gmae
Select Survival
Select Spaced Out Mode
Select the frosty planet dlc starting planet
Start Colony

### Player.log

ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index

System.ThrowHelper.ThrowArgumentOutOfRangeException (System.ExceptionArgument argument, System.ExceptionResource resource) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.ThrowHelper.ThrowArgumentOutOfRangeException () (at <695d1cc93cca45069c528c15c9fdd749>:0)
MinionSelectScreen+<SetDefaultMinionsRoutine>d__5.MoveNext () (at <043309e6f0914d9f9e207a782760f195>:0)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <72b60a3dd8cd4f12a155b761a1af9144>:0)

Build: U52-622509-SC

**Comment by Sgt-Imalas** [comment]
Ty, that explains the crash

**Comment by Sgt-Imalas** [comment]
fixed with version 7.1.1
