### ISSUE TITLE
[Synchronize Mods] DLC synchronization incomplete

### ISSUE THREAD

**Issue by konny87** [Sgt-Imalas/Sgt_Imalas-Oni-Mods#12]
Hey SGT_Imalas, after synchronization the Mods in a Spaced Out Savefile, not all mods were synced.

All of Ony's mods didn't load and weren't listed. For example:
DGSM - Duplicants Generation Settings Manager // by @Ony 👾
Schedule Master // by @Ony 👾
Research Manager // by @Ony 👾

I hope you or Ony can fix it :)
Thanks and Kind regards
Konny87

**Comment by Sgt-Imalas** [comment]
Fixed in 2.1
