### ISSUE TITLE
[BUG]: Localization translations appear in English when using mod

### ISSUE THREAD

**Issue by CritGB** [Sgt-Imalas/Sgt_Imalas-Oni-Mods#120]
### Which Mod?

Duplicant Stat Selector , Rocketry Expanded (DLC) ~

### Description of the bug/crash

When using the mode, the tooltip will show the translation in English.

![제목 없음-1](https://github.com/user-attachments/assets/b2ea48c3-4c2e-4c67-89c3-33388e2670dc)

### Steps To Reproduce

Enable mods and set to another language

### Player.log

.

**Comment by Sgt-Imalas** [comment]
Fixed for DSS in 7.1.3

**Comment by Sgt-Imalas** [comment]
Fixed for Rocketry Expanded in 2.8.7
