### ISSUE TITLE
[BUG]: Inconsistent Geyser/POI/Plants Generation in custom sized asteroids.

### ISSUE THREAD

**Issue by ArlEamon** [Sgt-Imalas/Sgt_Imalas-Oni-Mods#122]
### Which Mod?

Cluster Generation Manager [Vanilla/DLC]

### Description of the bug/crash

1 - If I start a game with nothing touched and save it as preset; the geyses are generated the same after I load it and start a new game.

2 - If I start a game with standard sized asteroids and also add some traits to the asteroids; the geysers are generated the same every time I load it. So traits do not affect the geyser generation.

3 - If I don't touch some asteroids, but change the size of some others; here is what happens. The untouched asteroids generate geysers and all other things the same. But custom sized ones generate different geysers, POI's and plants.

4 - Other than that, tile generation seems to be the same no matter if custom sized or not. To note here, the same seed number of custom sized asteroids generate different tiles than standard sized asteroids. But they are consistent in every preset load.

### Steps To Reproduce

1. Create a new preset
2. Change the size of some asteroids
3. Save the preset and start a game with that preset
4. Exit to main menu and start a new game loading the preset saved in 3
5. Check all asteroids in both saves if they have the same Geysers, POI's, Plants.
6. While custom sized asteroids do not generate the same Geysers, POI's, Plants; standard sized ones do.

### Player.log

[Player.log](https://github.com/user-attachments/files/16367207/Player.log)

**Comment by ArlEamon** [comment]
I don't if it has something to do with the bug but; when you save an asteroid with a custom size and load the preset; the default asteroid size selection options are broken too. I can't define it very well; because English is not my mother language. I am adding two screenshots. First one is before the preset is saved, second one is when the preset is loaded. This does not happen with standard sized asteroids.
![Cluster Generation Manager - Bug in asteroid creation 1](https://github.com/user-attachments/assets/8de84060-2bba-409d-934a-85c91ff461fd)
![Cluster Generation Manager - Bug in asteroid creation 2](https://github.com/user-attachments/assets/b04791e4-0c7f-4719-9101-92e462dc75e9)

**Comment by ArlEamon** [comment]
Here are the 3 combinations of presets I made for bug testing.
[zzzzzzzz_test_for_mod_1-2_32A660.json](https://github.com/user-attachments/files/16367377/zzzzzzzz_test_for_mod_1-2_32A660.json)
[zzzzzzzz_test_for_mod_3-4_E87E34.json](https://github.com/user-attachments/files/16367378/zzzzzzzz_test_for_mod_3-4_E87E34.json)
[zzzzzzzz_test_for_mod_5-6_A5459F.json](https://github.com/user-attachments/files/16367379/zzzzzzzz_test_for_mod_5-6_A5459F.json)

**Comment by Sgt-Imalas** [comment]
very helpful log, ty.
that might show the bug already, the geyser rolls are different in the two generations in that log (they shouldnt be)

**Comment by Sgt-Imalas** [comment]
update on that:
something within the randomizer for geysers is altered on your machine, doesnt happen on mine, this is why I couldnt replicate it.
I threw out a part from that that _could_ have been causing that, but I cannot test it myself

**Comment by ArlEamon** [comment]
I will try it when I get to my computer (1 hour maybe). Thanks.

25 Tem 2024 Per 15:01 tarihinde SGT_Imalas ***@***.***> şunu
yazdı:

**Comment by ArlEamon** [comment]
For this part; I don't know how it is altered. But; I uninstalled and
reinstalled a few times while trying. That should have reset the
alteration. Somehow geyser generation is broken after the last version.

25 Tem 2024 Per 14:56 tarihinde SGT_Imalas ***@***.***> şunu
yazdı:

**Comment by Sgt-Imalas** [comment]
Can you post me a log with the teat version?

**Comment by Sgt-Imalas** [comment]
the alteration comes potentially from differences in hardware, likely not something that can be adjusted

**Comment by Sgt-Imalas** [comment]
ok, so far that did NOT fix the bug :(

**Comment by Sgt-Imalas** [comment]
it just happened to roll similarly enough to not change geysers

**Comment by ArlEamon** [comment]
I don't understand much from the player.log. But as I said; geysers and POI's are generated the same at the exact same location. But plants are different everytime.

**Comment by Sgt-Imalas** [comment]
> geysers and POI's are generated the same 

this happened randomly sadly, the values were still different (which they shouldnt be, but I have no idea why they arent)

**Comment by Sgt-Imalas** [comment]
[ClusterTraitGenerationManager_dev.zip](https://github.com/user-attachments/files/16381046/ClusterTraitGenerationManager_dev.zip)
can you retry it with this version? 
I changed the way it gets the random values away from that which seems to be inconsistent

**Comment by Sgt-Imalas** [comment]
> I don't understand much from the player.log. 

geyser count scales with world size, for smaller asteroids, those geyser POIs that generate once with default size become a chance.
the way that chance is randomized, it _should_ be consistent each time as it uses the world seed for a seeded random.
for some reason, this does not apply for your computer

(you can find "Adjusting geyser roll amount to worldsize " in the log, this is where it rolls for that)

**Comment by Sgt-Imalas** [comment]
slightly adjusted version:
[ClusterTraitGenerationManager_dev.zip](https://github.com/user-attachments/files/16381397/ClusterTraitGenerationManager_dev.zip)

**Comment by Sgt-Imalas** [comment]
[Uploading ClusterTraitGenerationManager_dev.zip…]()
another adjustment

**Comment by ArlEamon** [comment]
> another adjustment: [ClusterTraitGenerationManager_dev.zip](https://github.com/user-attachments/files/16381497/ClusterTraitGenerationManager_dev.zip)

For this one it is not working. Player.log is below.
[Player.log](https://github.com/user-attachments/files/16381519/Player.log)


I will try the previous one as well

**Comment by ArlEamon** [comment]
I think I messed up the versions while downloading sorry. Will try again shortly

**Comment by Sgt-Imalas** [comment]
should be version 4.2.5.2

here would be 4.2.5.3:
[ClusterTraitGenerationManager_dev.zip](https://github.com/user-attachments/files/16381612/ClusterTraitGenerationManager_dev.zip)

**Comment by ArlEamon** [comment]
For 4.2.5.3 geysers and POI's are the same but plants are different.

Should I try the previous ones?

[Player.log](https://github.com/user-attachments/files/16381735/Player.log)

**Comment by Sgt-Imalas** [comment]
thats progress.

**Comment by ArlEamon** [comment]
I tried 4.2.5.2 also. Geysers and POI's are same but plants are different again.

[Player.log](https://github.com/user-attachments/files/16381851/Player.log)

**Comment by Sgt-Imalas** [comment]
finally something I can replicate

**Comment by ArlEamon** [comment]
So that is not just for my computer.

**Comment by Sgt-Imalas** [comment]
yep. only the geysers altering was.
What is/was causing that is beyond me, potentially a badly written mod that manipulates System.Random in some way.
Switching to the game internal KRandom fixed that at least.

**Comment by Sgt-Imalas** [comment]
for the plants I suspect floating point inacuracies

**Comment by Sgt-Imalas** [comment]
can you test if this version here fixes the plants:

[ClusterTraitGenerationManager_dev.zip](https://github.com/user-attachments/files/16382184/ClusterTraitGenerationManager_dev.zip)

**Comment by ArlEamon** [comment]
Hi. Sorry for the late reply. I was a little busy.

The last version you sent (4.2.5.4) is working with plants also. Geysers, POI's and plants all are generated consistently.

I don't know if it matters about generation but, plant growth rates are always different in new generations. Plants were at same growth rate with update 4.2.3 and previous ones.

[Player.log](https://github.com/user-attachments/files/16382626/Player.log)

**Comment by ArlEamon** [comment]
Another note.
I don't know it is a mod thing or not but, my geysers listed in map overlay menu has unique codes. They are shown as "Cool Slush Geyser RA13-2" With every geeneration unique code changes. I can't remember how it was before update 4.2.3. I just added this for information in case it helps about solution.

![Geyser names and codes in map overlay](https://github.com/user-attachments/assets/42f344d6-de4e-44f3-9152-fe188b05e77d)

**Comment by Sgt-Imalas** [comment]
> The last version you sent (4.2.5.4) is working with plants also. Geysers, POI's and plants all are generated consistently.

thats is good enough for me, ty for the assistence with finding this bug, it was a great help

**Comment by ArlEamon** [comment]
Fair enough.
I really apreciate your work very much. I'm glad that I helped for the bug, and it was fun testing. Thank you.

**Comment by ArlEamon** [comment]
Will you update the steam build?

**Comment by Sgt-Imalas** [comment]
I will probably do that tomorrow, today was draining.
I will update this issue when I do

**Comment by Sgt-Imalas** [comment]
released on steam as 4.2.5
