### ISSUE TITLE
[BUG]: game wont load

### ISSUE THREAD

**Issue by lelliam** [Sgt-Imalas/Sgt_Imalas-Oni-Mods#123]
### Which Mod?

Cluster Generation Manager

### Description of the bug/crash

forces restart over and over again

### Steps To Reproduce

open ONI with Cluster Generation Manager enabled

### Player.log

no player log as bug occurs upon opening the game

**Comment by Sgt-Imalas** [comment]
this is a bug of the game updating system, you can circumvent it by dismissing the "restart" message with escape, then using mod updater to force update the mod
