### ISSUE TITLE
[BUG]: Game crash if an older preset from before v4.2.6 is loaded

### ISSUE THREAD

**Issue by ArlEamon** [Sgt-Imalas/Sgt_Imalas-Oni-Mods#124]
### Which Mod?

Cluster Generation Manager [Vanilla/DLC]

### Description of the bug/crash

Getting "MISSING.STRINGS.UI.CGMEXPORT_SIDEMENUS.PRESETWINDOW.CGM....." when I select a preset. (error code continues but does not fit into the screen.)

When I press apply I get a crash. (Not all presets crash though)

### Steps To Reproduce

Choose an older preset. You will get the error on preset selection screen.  Not all presets give this error. When you get an error with the preset try to apply it. You will get a crash.

### Player.log

[Player-prev.log](https://github.com/user-attachments/files/16396385/Player-prev.log)

**Comment by ArlEamon** [comment]
Also crash log is here


NullReferenceException: Object reference not set to an instance of an object

ClusterTraitGenerationManager.ClusterData.CGSMClusterManager+<>c.<GenerateClusterLayoutFromCustomData>b__40_0 (ClusterTraitGenerationManager.ClusterData.StarmapItem item) (at <d4af71eb3fb245f9b075641ae8598178>:0)
System.Linq.EnumerableSorter`2[TElement,TKey].ComputeKeys (TElement[] elements, System.Int32 count) (at <351e49e2a5bf4fd6beabb458ce2255f3>:0)
System.Linq.EnumerableSorter`1[TElement].ComputeMap (TElement[] elements, System.Int32 count) (at <351e49e2a5bf4fd6beabb458ce2255f3>:0)
System.Linq.EnumerableSorter`1[TElement].Sort (TElement[] elements, System.Int32 count) (at <351e49e2a5bf4fd6beabb458ce2255f3>:0)
System.Linq.OrderedEnumerable`1[TElement].SortedMap (System.Linq.Buffer`1[TElement] buffer) (at <351e49e2a5bf4fd6beabb458ce2255f3>:0)
System.Linq.OrderedEnumerable`1[TElement].ToList () (at <351e49e2a5bf4fd6beabb458ce2255f3>:0)
System.Linq.Enumerable.ToList[TSource] (System.Collections.Generic.IEnumerable`1[T] source) (at <351e49e2a5bf4fd6beabb458ce2255f3>:0)
ClusterTraitGenerationManager.ClusterData.CGSMClusterManager.GenerateClusterLayoutFromCustomData (System.Boolean log) (at <d4af71eb3fb245f9b075641ae8598178>:0)
ClusterTraitGenerationManager.ClusterData.CGSMClusterManager.get_GeneratedLayout () (at <d4af71eb3fb245f9b075641ae8598178>:0)
ClusterTraitGenerationManager.UI.SO_StarmapEditor.StarmapToolkit.RebuildGrid () (at <d4af71eb3fb245f9b075641ae8598178>:0)
ClusterTraitGenerationManager.UI.Screens.CGM_MainScreen_UnityScreen.ResetSOStarmap (System.Boolean reset) (at <d4af71eb3fb245f9b075641ae8598178>:0)
ClusterTraitGenerationManager.UI.Screens.CGM_MainScreen_UnityScreen.RebuildStarmap (System.Boolean reset) (at <d4af71eb3fb245f9b075641ae8598178>:0)
ClusterTraitGenerationManager.UI.Screens.CGM_MainScreen_UnityScreen.<InitializeItemSettings>b__177_22 () (at <d4af71eb3fb245f9b075641ae8598178>:0)
ClusterTraitGenerationManager.UnityPresetScreen.<Init>b__39_2 () (at <d4af71eb3fb245f9b075641ae8598178>:0)
UtilLibs.UIcmp.FButton.OnPointerUp (UnityEngine.EventSystems.PointerEventData eventData) (at <d4af71eb3fb245f9b075641ae8598178>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IPointerUpHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at <e9635660f69b4d9d84c085aeda3be353>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) (at <e9635660f69b4d9d84c085aeda3be353>:0)
UnityEngine.EventSystems.EventSystem:Update()

Build: U52-623711-SCD

**Comment by Sgt-Imalas** [comment]
are there random planets in these presets that crash?

**Comment by ArlEamon** [comment]
I'm also sending presets that are causing the error.

[1_+12Water_+1_Beeta_2E02C9.json](https://github.com/user-attachments/files/16396431/1_%2B12Water_%2B1_Beeta_2E02C9.json)
[2_+11Water_+2_Beeta_+_4_Bitki_75A2F6.json](https://github.com/user-attachments/files/16396432/2_%2B11Water_%2B2_Beeta_%2B_4_Bitki_75A2F6.json)
[Ati_Starting_Cluster_25DBFA.json](https://github.com/user-attachments/files/16396433/Ati_Starting_Cluster_25DBFA.json)
[zzzz_Good_Start_-_1_68BB9D.json](https://github.com/user-attachments/files/16396434/zzzz_Good_Start_-_1_68BB9D.json)
[zzzz_Good_Start_-_2_086D50.json](https://github.com/user-attachments/files/16396435/zzzz_Good_Start_-_2_086D50.json)
[zzzz_Good_Start_-_3_-_Best_6DC838.json](https://github.com/user-attachments/files/16396436/zzzz_Good_Start_-_3_-_Best_6DC838.json)

**Comment by ArlEamon** [comment]
No. There aren't any random planets.

**Comment by ArlEamon** [comment]
I have deletes one of the presets.

There is a strange behaviour. After I get the error when selecting one of the broken ones, if I select a working one it gives an error too; but works.

**Comment by ArlEamon** [comment]
I should also point out that all of the broken presets have Ceres Minor as Outer Asteroid.

I have older presets without Ceres Minor and they are working.

**Comment by Sgt-Imalas** [comment]
the one in your log seems to be missing SmallOilySwampOuter, which is an outer variant of SmallWarpOilySwamp.

**Comment by Sgt-Imalas** [comment]
it is missing, because apparently Klei removed it from the Terra Cluster recently, leading to it no longer getting loaded into the game

**Comment by ArlEamon** [comment]
LOL. So they won't work no matter what you do.

**Comment by Sgt-Imalas** [comment]
the asteroid is still there, I can force the game to still load it (like with that one variant of moonlet

**Comment by Sgt-Imalas** [comment]
this might or might not be something that broke with either last nights hotfix or the frosty planet release and it just did not trigger until now

**Comment by ArlEamon** [comment]
I checked and yes it is not there anymore as a selectable asteroid. Only the normal sized one is there.

**Comment by ArlEamon** [comment]
> this might or might not be something that broke with either last nights hotfix or the frosty planet release and it just did not trigger until now

It was there until last nights update I think. Because I created these presets after Fosty Pack. They all have Ceres Minor.

I thought it was something to do with that asteroid, but it doesn't seem to be the case

**Comment by ArlEamon** [comment]
I don't think; I am sure. Because I recreated the same preset from the beginning while testing the bug before.

**Comment by ArlEamon** [comment]
I think you don't have to work for it; if it is already removed.

But if you like to do so; I won't say no don't do it. :)

**Comment by Sgt-Imalas** [comment]
it is not removed (from the files at least)

but the game only loads asteroids that are present in at least one cluster
(for that reason there is also one moonlet variant from the moonlet starts that is in the files, but not loaded)

**Comment by Sgt-Imalas** [comment]
So I'll have to force the game to load the asteroid again (and add better "missing asteroids" handling)

**Comment by ArlEamon** [comment]
Yes it would of course be better to have that included in the mod.

**Comment by Sgt-Imalas** [comment]
MiniMetallicSwampyWarp is the one not loaded by default

**Comment by ArlEamon** [comment]
It might be a game bug

**Comment by ArlEamon** [comment]
Do you have any connection with klei

**Comment by Sgt-Imalas** [comment]
it is by design (not good design, but still design)

since there is no moonlet cluster where metallic swampy is a teleporter asteroid

**Comment by Sgt-Imalas** [comment]
> Do you have any connection with klei

sadly not

**Comment by ArlEamon** [comment]
Ok then it's up to you if you work for it.

It is of course better to have a failsafe code in the mod. But also it is what it is. So you don't have to fix this. Because in the future there might be more dramatic changes to asteroids, which you would have to include every possible change in your code.

**Comment by ArlEamon** [comment]
In patch notes it doesn't mention any of the asteroids removal. I still think this might be a bug.

**Comment by Sgt-Imalas** [comment]
the file has a note at the top:
"# Unused - Was used for VanillaSandstoneCluster"

**Comment by Sgt-Imalas** [comment]
oh.
and SmallRadioactiveLandingSite has met the same fate

**Comment by ArlEamon** [comment]
So this was left in the game until sometime.

Then you shouldn't be working on a fix for this. This might get removed completely in the future; which would brake the mod again. (if you use those files of course)

**Comment by Sgt-Imalas** [comment]
I can readd those files over the mod in the future

**Comment by ArlEamon** [comment]
What will happen when they get removed completely?

**Comment by ArlEamon** [comment]
Oh I miss read. You are talking about putting those asteroid files into the mod.

**Comment by Sgt-Imalas** [comment]
in theory I can readd them as modded asteroids in CGM

**Comment by Sgt-Imalas** [comment]
but it might be better to instead add redirects for old presets

**Comment by ArlEamon** [comment]
Redirects might be a better choice for now.

**Comment by ArlEamon** [comment]
Or you might add a warning about removed asteroids instead of an error, and do not allow loading that preset.

Because you will have to put redirects every time an asteroid is removed.

**Comment by ArlEamon** [comment]
Klei seems to be going after biome scrambling. This would also reduce the count of asteroids needed. You can get every type of biome on whichever asteroid you want with scrambling.

**Comment by Sgt-Imalas** [comment]
thats my assumption as well - remove the "duplicate" smaller asteroid that was unfit for biome mixing

**Comment by ArlEamon** [comment]
Yep. So what will yo do? Will you give a warning to change the preset; or try to redirect older asteroids?

**Comment by Sgt-Imalas** [comment]
both for now
redirect if possible + warning counter

**Comment by ArlEamon** [comment]
Ok. Good luck then.

I will always be pleased to help you if I'm available. Don't bother to ask for help any time.

**Comment by ArlEamon** [comment]
Still not working.

If I don't change anything from an older not working preset, I get this error.

![Cluster Generation Manager - Bug in asteroid creation](https://github.com/user-attachments/assets/917f7f0f-103a-484c-8c3c-e035cb38a9a2)

I'm familiar with this error; it is caused by small asteroids; where the game cannot generate POI's because of lack of space.

After I got this error I changed that asteroids size to a standard and this time I got a crash. The crash occures after asteroid generation is complete when it says "Success! Space adventure awaits." on the generation screen.


[Player-prev.log](https://github.com/user-attachments/files/16397238/Player-prev.log)

[crashlog.txt](https://github.com/user-attachments/files/16397248/crashlog.txt)

**Comment by Sgt-Imalas** [comment]
ah rip I forgot to add that override to starmap locations too

**Comment by ArlEamon** [comment]
LOL. You need a full time tester. :)

**Comment by Sgt-Imalas** [comment]
and work with more sleep

**Comment by ArlEamon** [comment]
Yep I need that too :)

**Comment by Sgt-Imalas** [comment]
here, that should fix it:
[ClusterTraitGenerationManager_dev.zip](https://github.com/user-attachments/files/16397354/ClusterTraitGenerationManager_dev.zip)

**Comment by ArlEamon** [comment]
I can confirm that it is working with older presets.

Generation is consistent with geysers, POI's and plants (growth rate is different though)

**Comment by ArlEamon** [comment]
Last nights modifications changed another thing. 

Before last night when I changed a Space POI location in starmap; I was getting a different geyser generation. Tiles, POI's and plants were the same but geysers were changing. They were still consistent with preset load. So with same starmap, same seed, same planetoids; I was getting the exact same generation.

Now; if I change a space POI location in starmap; I always get the same geysers. Other things are also the same. Nothing changes at all.

Changing a space POI location was a quick geyser reroll technique for me with a desired (and of course  the same) tile, POI and plant generation.

**Comment by Sgt-Imalas** [comment]
that sounds like something weird with that afformentioned random doing weird things, because they _should_ not influence each other

**Comment by ArlEamon** [comment]
So I should understand this as it wasn't supposed to be like that. Am I right?

**Comment by Sgt-Imalas** [comment]
yes

**Comment by ArlEamon** [comment]
Sad. It was a usefull "feature" of a bug then. :)

Thanks for your work and time.

**Comment by Sgt-Imalas** [comment]
its likely a similar thing that caused presets on your machine to roll different geysers than the original world

**Comment by Sgt-Imalas** [comment]
the seeded random *should* have rolled identical, but it didnt

**Comment by ArlEamon** [comment]
LOL I was really getting used to it. Trying to get a perfect generation with it.

**Comment by Sgt-Imalas** [comment]
geyser overriding is now also a feature
