### ISSUE TITLE
[BUG]: Crash when replacing Extended Solo Spacefarer Nosecone

### ISSUE THREAD

**Issue by wasserts** [Sgt-Imalas/Sgt_Imalas-Oni-Mods#125]
### Which Mod?

Rocketry Expanded

### Description of the bug/crash

The game crashes when replacing an "Extended Solo Spacefarer Nosecone" with another module (e.g. normal "Solo Spacefarer Nosecone"). It happened in Sandbox mode with all other mods disabled (except Mod-Managers).

### Steps To Reproduce

1. Build Rocket Platform
2. Build Extended Solo Spacefarer Nosecone
3. Replace (Gear Button) Nosecone with another Module
4. Crash

### Player.log

[Player.log](https://github.com/user-attachments/files/16573731/Player.log)

**Comment by Sgt-Imalas** [comment]
thats a vanilla crash
