### ISSUE TITLE
[BUG]: Starting a new game with 1 duplicant bugs it out

### ISSUE THREAD

**Issue by Sad-theFaceless** [Sgt-Imalas/Sgt_Imalas-Oni-Mods#126]
### Which Mod?

Duplicant Stat Selector

### Description of the bug/crash

Upon embarking on a new game with 1 dupe, the duplicant spawns but the game is seemingly stuck (not frozen). Pressing the ESC key 3+ times is required to unstuck it. The regular "Alert" popup (check screenshot below) does NOT appear at the beginning.

![image](https://github.com/user-attachments/assets/19c7b2ae-a644-4f5f-9f9e-8b36fdecb3cb)

Note that I don't get the bug with 2 or 4+ dupes.

### Steps To Reproduce

- New Game > Any Game Mode > Any Asteroid Style > Start Game
- Click on "Remove Slot" on 2 duplicants to only have 1 remaining
- Embark

This is 100% reproductible in my end, the bug always happens.

### Player.log

[Player.log](https://github.com/user-attachments/files/16590960/Player.log)

**Comment by Sgt-Imalas** [comment]
fixed with release 7.3.1
