### ISSUE TITLE
Automation Port Drillcone Bug, and unused Config

### ISSUE THREAD

**Issue by XXilay** [Sgt-Imalas/Sgt_Imalas-Oni-Mods#13]
Hey! Looks like i found a bug. 
The laser drillcones Automation port stays on red even when the storage is full. 
This only seems to occur tho when the rocket already flew out to somewhere already and came back. 

Also theres a config option for an RTG Decay time even tho theres no such rocket part from the mod.

**Comment by Sgt-Imalas** [comment]
ah, another bug at the drillcone. I will adress it in the next update.
the rtg option is a teaser for the next update

**Comment by XXilay** [comment]
I will once it reoccurs , but there's honestly not much to show. 
The automation port will still be red and even hovering over it will highlight the "Otherwise RED signal" text.
While when clicking on the module, it will clearly say 6000/6000 bolts, and radbolts will just fly past its input port

**Comment by hwp163com** [comment]
Save and load could fix this, I'm not sure what caused this to happen.

**Comment by Sgt-Imalas** [comment]
this honestly sounds like something coming from the vanilla radbolt storage (since Im reusing that logic).
I'll close this issue for now.
