### ISSUE TITLE
[BUG]: Better rebuilding mod causes a game crash

### ISSUE THREAD

**Issue by nased0** [Sgt-Imalas/Sgt_Imalas-Oni-Mods#134]
### Which Mod?

Better rebuilding

### Description of the bug/crash

The game crashes about 25 seconds after loading the affected savegame.
After disabling only the Better rebuilding mod only, the game does not crash.
[Player.log](https://github.com/user-attachments/files/17608387/Player.log)
https://pastebin.com/WTj3Y3xU
https://pastebin.com/s2CYCJdF

### Steps To Reproduce

Download my save from
https://www.4shared.com/s/fJiHt-7LNku
Load necessary mods
Start the game, wait half a minute until it crashes.

### Player.log

https://pastebin.com/WTj3Y3xU
https://pastebin.com/s2CYCJdF
Download my save from
https://www.4shared.com/s/fJiHt-7LNku
Load necessary mods
Start the game, wait half a minute until it crashes.

**Comment by Sgt-Imalas** [comment]
fixed in latest version
