### ISSUE TITLE
[BUG]: The game crashes when I try to load a preset in the CGM mod.

### ISSUE THREAD

**Issue by DarkEviL88** [Sgt-Imalas/Sgt_Imalas-Oni-Mods#138]
### Which Mod?

Cluster Generation Manager

### Description of the bug/crash

The game crashes when I try to load a preset.

NullReferenceException: Object reference not set to an instance of an object

CustomGameSettings.SetMixingSetting (Klei.CustomSettings.SettingConfig config, System.String value, System.Boolean notify) (at <96bf83e479e841629616de31cacb5606>:0)
(wrapper dynamic-method) CustomGameSettings.CustomGameSettings.SetMixingSetting_Patch1(CustomGameSettings,Klei.CustomSettings.SettingConfig,string)
ClusterTraitGenerationManager.CustomClusterSettingsPreset.SetMixingSettings (Klei.CustomSettings.MixingSettingConfig mixing, System.Object valueId) (at <fe4b21c416364fb3b444a5dac6dd9b16>:0)
ClusterTraitGenerationManager.CustomClusterSettingsPreset.ApplyGameSettings () (at <fe4b21c416364fb3b444a5dac6dd9b16>:0)
ClusterTraitGenerationManager.CustomClusterSettingsPreset.ApplyPreset () (at <fe4b21c416364fb3b444a5dac6dd9b16>:0)
ClusterTraitGenerationManager.UnityPresetScreen.<Init>b__39_2 () (at <fe4b21c416364fb3b444a5dac6dd9b16>:0)
UtilLibs.UIcmp.FButton.OnPointerUp (UnityEngine.EventSystems.PointerEventData eventData) (at <fe4b21c416364fb3b444a5dac6dd9b16>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IPointerUpHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at <6405a4abeb6c490388904d755e3f6782>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) (at <6405a4abeb6c490388904d755e3f6782>:0)
UnityEngine.EventSystems.EventSystem:Update()

Build: U53-642695-SC

### Steps To Reproduce

Start the game
Go to cluster setup
Go to presets and click load preset

### Player.log

[Player.log](https://github.com/user-attachments/files/17870851/Player.log)

**Comment by Sgt-Imalas** [comment]
not that unexpected tbh, I was forced to rush that update

**Comment by Sgt-Imalas** [comment]
should be fixed with 5.0.1

**Comment by Sgt-Imalas** [comment]
aand i broke preset traits..... -> 5.0.2
