### ISSUE TITLE
[BUG]: rebuilder error crashed game

### ISSUE THREAD

**Issue by GScully** [Sgt-Imalas/Sgt_Imalas-Oni-Mods#139]
### Which Mod?

better rebuilding

### Description of the bug/crash

Game crashed trying to rebuild blastshot shooter.

NullReferenceException: Object reference not set to an instance of an object

FlatTagFilterable.OnCopySettings (System.Object data) (at <a68254e14f8f4e0b99360e84d2e9b774>:0)
EventSystem.Trigger (UnityEngine.GameObject go, System.Int32 hash, System.Object data) (at <5dfe0ae6d45544628b5ae53433ea03d4>:0)
EventExtensions.Trigger (UnityEngine.GameObject go, System.Int32 hash, System.Object data) (at <5dfe0ae6d45544628b5ae53433ea03d4>:0)
RebuildPreserve.Patches+ApplySettingsToNewBuilding+<>c__DisplayClass2_0.<OnBuildingConstructed>b__0 (System.Object _) (at <46116d6025de463f8118078144066635>:0)
Scheduler.Update () (at <a68254e14f8f4e0b99360e84d2e9b774>:0)
GameScheduler.Update () (at <a68254e14f8f4e0b99360e84d2e9b774>:0)

Build: U53-643502-SCD

### Steps To Reproduce

use mod and have it rebuild a blastshot shooter

### Player.log

[Player.log](https://github.com/user-attachments/files/17926452/Player.log)

**Comment by Sgt-Imalas** [comment]
fixed in latest version
