### ISSUE TITLE
Crash with "Modlist Manager"

### ISSUE THREAD

**Issue by alexander-cg** [Sgt-Imalas/Sgt_Imalas-Oni-Mods#14]
Hi, I uninstalled and deleted my "ONI" folder, then reinstalled. With no mods download, I subscribed to you "Modlist manager" and received the following error message.

NullReferenceException: Object reference not set to an instance of an object

KMod.ZipFile.CopyTo (System.String path, System.Collections.Generic.List`1[T] extensions) (at <6ab6b57553ed449280aa2485c86e9aab>:0)
KMod.Mod.Install () (at <6ab6b57553ed449280aa2485c86e9aab>:0)
KMod.Manager.Install (KMod.Mod mod) (at <6ab6b57553ed449280aa2485c86e9aab>:0)
KMod.Manager.Subscribe (KMod.Mod mod, System.Object caller) (at <6ab6b57553ed449280aa2485c86e9aab>:0)
KMod.Steam.UpdateMods (System.Collections.Generic.IEnumerable`1[T] added, System.Collections.Generic.IEnumerable`1[T] updated, System.Collections.Generic.IEnumerable`1[T] removed, System.Collections.Generic.IEnumerable`1[T] loaded_previews) (at <6ab6b57553ed449280aa2485c86e9aab>:0)
SteamUGCService.Update () (at <6ab6b57553ed449280aa2485c86e9aab>:0)

Build: U43-525812-S
[ONI Crash Log.txt](https://github.com/Sgt-Imalas/Sgt_Imalas-Oni-Mods/files/9711599/ONI.Crash.Log.txt)

**Comment by Sgt-Imalas** [comment]
I need the log to work with

**Comment by levahka0909** [comment]
My game crashing when i building the cryopod! Link to the log: https://pastebin.com/RTn6hQd0

**Comment by Sgt-Imalas** [comment]
> My game crashing when i building the cryopod! Link to the log: https://pastebin.com/RTn6hQd0

a) that log does not contain any crashes 
b) please open a separate issue

**Comment by Sgt-Imalas** [comment]
> Sorry about that. I've included the logs this time. [Player.log](https://github.com/Sgt-Imalas/Sgt_Imalas-Oni-Mods/files/9730985/Player.log)

so, for some reason the following happens here:
 The game tries to load the german localisation file, but fails to acess it since the file seems to be nonexistent (maybe also bc its not on any local drive (?)).
 maybe a reinstallation can fix that

**Comment by Sgt-Imalas** [comment]
(of the mod, so unsubscribe, then resubscribe while the game is running)
