### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by BlackWid0wz** [Sgt-Imalas/Sgt_Imalas-Oni-Mods#140]
### Which Mod?

Duplicant Stat Selector

### Description of the bug/crash

When i open the game the first box that appears says the mod is unistalled (image 1). When i go to the mods, it says that the mod is not compatible with the base game (image 2) and the Spaced Out DLC (image 3).
![Image 2](https://github.com/user-attachments/assets/3d131ab3-19a8-4b34-b9d3-8813e3317eeb)
![Image 3](https://github.com/user-attachments/assets/e0cc45f5-f6bb-4db8-bbff-2ed19ed10109)
![Image 1](https://github.com/user-attachments/assets/51b76023-babd-4c9c-b7f1-c5b39b884cdd)

### Steps To Reproduce

Open the game
Box shows the mod is uninstalled
Click Mods section on menu
It shows that DSS is not compatible with the game

### Player.log

Could'nt find the log

**Comment by Sgt-Imalas** [comment]
verify your game files+force update

this is a game issue, not mod issue

**Comment by Sgt-Imalas** [comment]
if the game still fails updating after that, you can grab a local download here:
https://github.com/Sgt-Imalas/Sgt_Imalas-Oni-Mods/releases/tag/AllMods_21_11_24
