### ISSUE TITLE
[BUG]: Duplicant Stat Selector [DSS]

### ISSUE THREAD

**Issue by Thotlax** [Sgt-Imalas/Sgt_Imalas-Oni-Mods#141]
### Which Mod?

"Duplicant Stat Selector [DSS]"

### Description of the bug/crash

Game crashes upon loading. Anytime it is enabled.

### Steps To Reproduce

1: enable Mod 
2: Restart ONI
3: Game crashes

### Player.log

[Player.log](https://github.com/user-attachments/files/18003242/Player.log)

**Comment by Sgt-Imalas** [comment]
Klei broke their internal versioning system logic with [Game Hotfix] - 644960

is now resolved
