### ISSUE TITLE
[BUG]: Mod stopped working

### ISSUE THREAD

**Issue by Din0boy138YT** [Sgt-Imalas/Sgt_Imalas-Oni-Mods#142]
### Which Mod?

Duplicant Stat Selector

### Description of the bug/crash

It says it's not compatible with spaced out and when I switched to base game it says not compatible with base game, it was working like a week ago

### Steps To Reproduce

Simply launch the game
![image](https://github.com/user-attachments/assets/5a27dac5-3122-44a0-a150-d2f3f0469fbd)
![image](https://github.com/user-attachments/assets/f693bd88-93da-443b-bf55-94be46734ee8)

### Player.log

_Doesn't show up in files_

**Comment by Sgt-Imalas** [comment]
Use force update, the game failed at unpacking the mod after an update.

**Comment by Din0boy138YT** [comment]
I tried that. it didnt work
