### ISSUE TITLE
[BUG]: Decor Pack S - Winters Delight [CTD]

### ISSUE THREAD

**Issue by Ashotep** [Sgt-Imalas/Sgt_Imalas-Oni-Mods#147]
### Which Mod?

Decor Pack S - Winters Delight

### Description of the bug/crash

Game crashed while in the decor view and checking various areas.

### Steps To Reproduce

I had a bunch of ice sculptures and snow falling in glass cases and I was in the decor menu viewing the decor effects.

### Player.log

[Player.log](https://github.com/user-attachments/files/18243093/Player.log)

**Comment by Sgt-Imalas** [comment]
Should be fixed with version 1.3 now.
