### ISSUE TITLE
Crashes with the new version

### ISSUE THREAD

**Issue by 4Donic** [Sgt-Imalas/Sgt_Imalas-Oni-Mods#15]
On startup, red text.

[Player.log](https://github.com/Sgt-Imalas/Sgt_Imalas-Oni-Mods/files/9727952/Player.log)

**Comment by Sgt-Imalas** [comment]
not my mod, I do not update dreckos

**Comment by Sgt-Imalas** [comment]
which mod

**Comment by 4Donic** [comment]
No-no, It was me who was stupid and thought that it was the satellite mod, you're all good, Im sorry
