### ISSUE TITLE
Crashing when i build the cryopod 

### ISSUE THREAD

**Issue by levahka0909** [Sgt-Imalas/Sgt_Imalas-Oni-Mods#16]
The mod for cryopod is crashing, NEW link to the log: https://pastebin.com/USA0yabF

**Comment by Sgt-Imalas** [comment]
that log still does not contain any crashes

**Comment by Sgt-Imalas** [comment]
I need a log from when the game crashes

**Comment by Sgt-Imalas** [comment]
Where to find the Log:
Windows:
C:\Users\%username%\AppData\LocalLow\Klei\Oxygen Not Included\Player.log
Mac:
~/Library/Logs/Klei/Oxygen Not Included/Player.log
Linux:
~/.config/unity3d/Klei/Oxygen Not Included/Player.log
