### ISSUE TITLE
Crash when rerolling with editor panel open

### ISSUE THREAD

**Issue by ragzilla** [Sgt-Imalas/Sgt_Imalas-Oni-Mods#17]
- Start new game
- Open editor panel for duplicant
- Click Reroll

[Player.log](https://github.com/Sgt-Imalas/Sgt_Imalas-Oni-Mods/files/9768797/Player.log)

**Comment by Sgt-Imalas** [comment]
for a start, well: dont do that.
ty for the report, ill try to disable the button in the next release

**Comment by Sgt-Imalas** [comment]
Fixed in 2.0.1
