### ISSUE TITLE
ONI game crashed on AI rocket launch

### ISSUE THREAD

**Issue by VestoSlipher1** [Sgt-Imalas/Sgt_Imalas-Oni-Mods#2]
As mentioned in the title the game crashed on launch of the rocket. I have tried rebuilding the rocket twice and the rocket base once. 
I have tried putting the AI module at the bottom (first crash) and at the top (second crash new base).
[ONI AI rocket first crash.txt](https://github.com/Sgt-Imalas/Sgt_Imalas-Oni-Mods/files/8832779/ONI.AI.rocket.first.crash.txt)
[ONI Ai rocket second crash.txt](https://github.com/Sgt-Imalas/Sgt_Imalas-Oni-Mods/files/8832780/ONI.Ai.rocket.second.crash.txt)
First rocket was steam engine, AI module, Large cargo, large cargo, small gas and drill head. Destination was a nearby field of aluminum ore, carbon dioxide gas and igneous rock
Second rocket was steam engine, Large cargo, large cargo, small gas, AI module and drill head. destination was open space next too the field mentioned above. 

I have one other mod which affects rockets and that is your mod Space Radiator. 
I also have quite a lot of other mods installed but none affect rockets. 
You are welcome too contact me for more information

**Comment by Sgt-Imalas** [comment]
crash fixed in update 1.2
