### ISSUE TITLE
Update "Rocketry Expanded" release package

### ISSUE THREAD

**Issue by SammalKM** [Sgt-Imalas/Sgt_Imalas-Oni-Mods#20]
Please update "Rocketry Expanded" release package.

Last  "Rocketry Expanded" release 1.0.2 package
https://github.com/Sgt-Imalas/Sgt_Imalas-Oni-Mods/releases/tag/v1.0.2_RocketryExpanded

**Comment by Sgt-Imalas** [comment]
https://github.com/Sgt-Imalas/Sgt_Imalas-Oni-Mods/releases/tag/v2.3.4_RocketryExpanded
