### ISSUE TITLE
Unable to build pipes with Fortified Rocket Platform

### ISSUE THREAD

**Issue by Fury1SOG** [Sgt-Imalas/Sgt_Imalas-Oni-Mods#23]
Hello,
When you try to build pipes behind the Fortified Rocket Platform, Dupes are unable to reach the 3 cells at the bottom middle of the platform. The pipes are displayed as "Unreachable Build." This does not occur with the stock Rocket Platform.

![Unreachable_Build](https://user-images.githubusercontent.com/26163817/197369096-27780515-4c25-4b2c-ae88-a43eff4909e7.png)

**Comment by Sgt-Imalas** [comment]
this happens due to the platform stopping meteors, the top tiles of the platform are solid.
To reach those pipes you need to access it from below, either by temporarily removing the insulated tile in the middle or by building the plaform one tile higher so the dupes can walk below it

**Comment by Fury1SOG** [comment]
Thank you very much for the quick reply. I understand that this is by design. 
Have a nice day!
