### ISSUE TITLE
Automation issue with radbolt miner nosecone.

### ISSUE THREAD

**Issue by Saltz2487** [Sgt-Imalas/Sgt_Imalas-Oni-Mods#26]
I have setup a system where the rocket lands, will recognize that the rocket needs radbolts, discharge the radbolt until full and then shut off. However, I have noticed that the radbolt miner nosecone, often times does not reset the signal until I reload the game and will instead send a red signal (even though its full of radbolts. Thank you!

**Comment by Sgt-Imalas** [comment]
fixed in 2.4.1
