### ISSUE TITLE
Cargo Transfer Issue (Gas)

### ISSUE THREAD

**Issue by Saltz2487** [Sgt-Imalas/Sgt_Imalas-Oni-Mods#28]
Hello once more, I've included a few screenshots to see if this may help tie this issue down. This may not be with your mod, however, prior to the last push, with the new rocket ports (which are super awesome btw), I have not had an issue uploading gas to a rocket. This was after I used the new insulated connection ports. Please note, the screenshots are after I attempted to troubleshoot by deconstructing two of the new rocket ports (insulated rocket port adapter) to link the rocket cargo uploading setup. I appreciate any  help you can provide. Only other rocket mod I have is AI controlled rockets. 

Problem 
I have built a system to upload oxygen into gas tanks for consumption in the rocket. The rocket gas loading has power, and oxygen piped in it. The pipes have no other gas other than oxygen and the rocket cargo is set for the appropriate gas, oxygen.  However, both loaders say cargo transfer complete. The rocket gas level is still zero. 

I made sure of the following
All connectors are powered.
No other gas is in the line or the uploaders other than oxygen.
A proper link is made from the rocket uploader to the rocket pad.
The rocket pad is enabled.
The rocket pad actually has a rocket on it.
The gas cargo is properly checked with the appropriate gas.

Things I have tried. 

I tried deleting the Cargo tank. No change. still says cargo transfer complete.
I tried deleting the cargo uploaders. No change. Still says cargo transfer complete and does not move. 
I tried deleting both insulated rocket port wall adapters and then replace them. No change.
I tried deleting both insulated rocket port wall adapaters and then building another connector (in this case a solid rocket port loader) No change. Still says same.
I tried making a brand new gas rocket port loader with power and gas. No change. Will not upload to that rocket.
I tried moving the rocket to another launch pad. No change. Will not upload regardless of the rocket pad.

![Automation Overview](https://user-images.githubusercontent.com/120794134/208801127-dc36fe31-31ba-4ec8-b1de-4142649a2359.jpg)
![Cargo Transfer Complete](https://user-images.githubusercontent.com/120794134/208801158-99124690-c1e4-4954-81d2-5357609025e1.jpg)
![Power Overview](https://user-images.githubusercontent.com/120794134/208801206-9957eacf-da12-47a9-bd17-5095c315e3e2.jpg)
![Gas Overlay](https://user-images.githubusercontent.com/120794134/208801228-4f46a4b4-868c-4a2a-a64a-d4dbab0f1fca.jpg)
![Gas Cargo Will not fill](https://user-images.githubusercontent.com/120794134/208801254-4d682a71-94fe-4191-97a3-a373c4378bda.jpg)

**Comment by Sgt-Imalas** [comment]
thx for the report, that seems to be a bug in my loading code (that logic is attached to the landing pad, so changing out the adapter building wont do anything, Ill need to fix the code that sets the loading state of the rocket pad).
Will try to fix later if I got the time

**Comment by Sgt-Imalas** [comment]
Should be Fixed in Release 2.4.2

**Comment by Saltz2487** [comment]
I appreciate you taking a look at it. Thank you for taking the time to make this mod and keep it updated.
