### ISSUE TITLE
Crash after storing a bee tiny in critter rocket module

### ISSUE THREAD

**Issue by Jo9221** [Sgt-Imalas/Sgt_Imalas-Oni-Mods#29]
I added the crash message and Player.log file
 Hope, it helps. Thank you

NullReferenceException: Object reference not set to an instance of an object

Rockets_TinyYetBig.Behaviours.CritterStasisChamberModule.AddCritterToStorage (UnityEngine.GameObject critter) (at <b30e49316e214380b04549af6a8d0be7>:0)
Rockets_TinyYetBig.Behaviours.CritterStasisChamberModule.Sim1000ms (System.Single dt) (at <b30e49316e214380b04549af6a8d0be7>:0)
SimAndRenderScheduler+Sim1000msUpdater.Update (ISim1000ms updater, System.Single dt) (at <fa50cdddb14a483d94f547557a674a42>:0)
UpdateBucketWithUpdater`1[DataType].Update (System.Single dt) (at <fa50cdddb14a483d94f547557a674a42>:0)
StateMachineUpdater+BucketGroup.AdvanceOneSubTick (System.Single dt) (at <fa50cdddb14a483d94f547557a674a42>:0)
StateMachineUpdater.AdvanceOneSimSubTick () (at <fa50cdddb14a483d94f547557a674a42>:0)
Game.SimEveryTick (System.Single dt) (at <d13cbb0b55a94ef09bb55c2436a6b8ee>:0)
Game.Update () (at <d13cbb0b55a94ef09bb55c2436a6b8ee>:0)

Build: U44-535842-SD
[Beeta Crash Player.log](https://github.com/Sgt-Imalas/Sgt_Imalas-Oni-Mods/files/10326239/Beeta.Crash.Player.log)

**Comment by Sgt-Imalas** [comment]
thx for the report, apparently it helps checking all edge cases.
should be fixed in 2.4.3
