### ISSUE TITLE
Cargo Transfer complete bug

### ISSUE THREAD

**Issue by Saltz2487** [Sgt-Imalas/Sgt_Imalas-Oni-Mods#30]
Cargo transfer is marked as complete on rockets despite room for cargo and appropriate filters set. This is similar to the gas loading cargo bug I noted before on rocket modules.

Thank you!

**Comment by Sgt-Imalas** [comment]
got a save game where that happens to share?

**Comment by Saltz2487** [comment]
Yes, let me bundle up a save with the mods I use so you dont have to go searching around. It isnt alot. Standby.

**Comment by Saltz2487** [comment]
https://drive.google.com/drive/folders/101FukaQ7s2xeQ7SbNNhSDWlGKGlRq9kH?usp=share_link
Link to the Rar with the save and mods folder.

To test the issue:
1. On Planet Pustualozn ; land the rocket named " Resin/Tungsten bus. It will not load the material despite the filters and cargo being set.
2. On Planet Gurgelin : Metal Mule 1 and 2 are both landed and will not accept new cargo.

Thanks for your help!

**Comment by Sgt-Imalas** [comment]
so, after some testing, it turns out there is probably no bug in my code: 
the Resin/Tungsten bus rocket had their storage max size set to 0Kg, increasing that fixed that rocket loading
two loaders on gurgelin had fish inside of their internal storage, blocking these loader from loading since there is no fridge cargo bay yet.
very nice base

**Comment by Saltz2487** [comment]
I must admit I am markedly embarrassed! Fish! In the cargo tank? Lol. How the hell? Probably hatched in flight. I had no idea. 

Well thank you for taking a look at it. I do appreciate and apologize for  wasting your time. Next time, I will be more diligent. 

Fish. Lolol

**Comment by Sgt-Imalas** [comment]
fish meat

**Comment by Saltz2487** [comment]
That's going to take forever to clean. Meep will not be happy. Take care and thanks again.
