### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by StrikerMack** [Sgt-Imalas/Sgt_Imalas-Oni-Mods#4]
Ai Controlled Rockets. Not sure why, crash log included.
[Oni Crash Log.txt](https://github.com/Sgt-Imalas/Sgt_Imalas-Oni-Mods/files/8886752/Oni.Crash.Log.txt)

**Comment by Sgt-Imalas** [comment]
Update the Mod & Rebuild the module; should fix it
