### ISSUE TITLE
[543530] Crash on Newest Testing Branch with Rocketry Expanded

### ISSUE THREAD

**Issue by Lbphero** [Sgt-Imalas/Sgt_Imalas-Oni-Mods#40]
It crashes like, on running of a colony. Same colony loads fine without rocketry expanded only.

[Player-prev.log](https://github.com/Sgt-Imalas/Sgt_Imalas-Oni-Mods/files/10770849/Player-prev.log)

**Comment by Sgt-Imalas** [comment]
normally: no support for preview builds
in this case: version 2.5.1.2 fixes it
