### ISSUE TITLE
[BUG]: Latest update causing crash on unpause

### ISSUE THREAD

**Issue by LawOfSynergy** [Sgt-Imalas/Sgt_Imalas-Oni-Mods#43]
### Description of the bug/crash

After the latest update, trying to unpause the game causes an instant crash.

### Steps To Reproduce

I am not sure how to reproduce the issue. The crash message (and the mods being disabled) seems to indicate a bad interaction between Rocketry Expanded and [High Pressure Applications](https://steamcommunity.com/sharedfiles/filedetails/?id=2806200110).

however, I have not been able to recreate the issue by using a high pressure pipe into a fuel loader (pumping ethanol) in a sandbox world.

If there are preferred steps for sending my save and/or mod list, then I would be happy to supply them.

### Player.log

Using pastebin since github is complaining body is too long:

https://pastebin.com/i8FFhGMt

**Comment by Sgt-Imalas** [comment]
fixed with version 2.5.3

**Comment by LawOfSynergy** [comment]
I was able to load the save and resume now. Thanks for the fix!
