### ISSUE TITLE
[BUG]: Crash on closing planetoid menu

### ISSUE THREAD

**Issue by ReddMudd** [Sgt-Imalas/Sgt_Imalas-Oni-Mods#45]
### Description of the bug/crash

The planetoid trait menu should have closed and not caused a crash.

### Steps To Reproduce

Open a planetoid trait add menu on new world creation and press Esc, closing the chosen planetoid and causing a crash upon the menu closing.

### Player.log

NullReferenceException

KMonoBehaviour.get_transform () (at <676c504a1fc44f1f988e436496061541>:0)
ClusterTraitGenerationManager.SelectedItemSettings.UpdateForSelected (ClusterTraitGenerationManager.CGSMClusterManager+StarmapItem SelectedPlanet) (at <f094c2905a2d455db6bbda0b4b29289b>:0)
ClusterTraitGenerationManager.SelectedItemSettings.UpdateUI () (at <f094c2905a2d455db6bbda0b4b29289b>:0)
ClusterTraitGenerationManager.SelectedItemSettings.<Init>b__22_10 () (at <f094c2905a2d455db6bbda0b4b29289b>:0)
ClusterTraitGenerationManager.TraitSelectorScreen.<Init>b__11_0 () (at <f094c2905a2d455db6bbda0b4b29289b>:0)
UtilLibs.UIcmp.FButton.OnPointerDown (UnityEngine.EventSystems.PointerEventData eventData) (at <f094c2905a2d455db6bbda0b4b29289b>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IPointerDownHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at <0b23117e1c7442f8b1842fe2f3bf6fcb>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) (at <0b23117e1c7442f8b1842fe2f3bf6fcb>:0)
UnityEngine.EventSystems.EventSystem:Update()

Build: U45-546664-S

**Comment by Sgt-Imalas** [comment]
thx for the report, fixed in 1.2.1
