### ISSUE TITLE
[BUG]: Crash when rocket pilot is summoned with Move Here Command Tile

### ISSUE THREAD

**Issue by jrharris42** [Sgt-Imalas/Sgt_Imalas-Oni-Mods#47]
### Description of the bug/crash

The Move Here Command Tile lets you pick rocket pilots as the dupe to summon, activating the tile causes a crash (since that dupe doesn't exist).  

I'd make the selection list not allow rocket pilots and also make sure if one was selected before going into the rocket, that nothing happens when they get summoned.   

### Steps To Reproduce

1. Put dupe into rocket and launch it somewhere far away (base game).
2. Build a Move Here Command Tile.
3. Choose the rocket pilot as the dupe to summon.
4. Activate the tile. 

(3 and 4 can be in any order)

### Player.log

[Player.log](https://github.com/Sgt-Imalas/Sgt_Imalas-Oni-Mods/files/11069144/Player.log)

**Comment by Sgt-Imalas** [comment]
fix deployed in 1.0.3
