### ISSUE TITLE
AI Controlled Rockets: Game crash after recent update

### ISSUE THREAD

**Issue by ezonius** [Sgt-Imalas/Sgt_Imalas-Oni-Mods#5]
I can load up my save game. But after I unpause, it crashes.

NullReferenceException: Object reference not set to an instance of an object

Util.KInstantiate (UnityEngine.GameObject original, UnityEngine.Vector3 position, UnityEngine.Quaternion rotation, UnityEngine.GameObject parent, System.String name, System.Boolean initialize_id, System.Int32 gameLayer) (at <8c239b169b544cce8b8bc7ddd2d09e10>:0)
GameUtil.KInstantiate (UnityEngine.GameObject original, UnityEngine.Vector3 position, Grid+SceneLayer sceneLayer, UnityEngine.GameObject parent, System.String name, System.Int32 gameLayer) (at <9411b2c55a4e44e68a95bd3ba148e05c>:0)
GameUtil.KInstantiate (UnityEngine.GameObject original, UnityEngine.Vector3 position, Grid+SceneLayer sceneLayer, System.String name, System.Int32 gameLayer) (at <9411b2c55a4e44e68a95bd3ba148e05c>:0)
KnastoronOniMods.RocketControlStationNoChorePrecondition.<MakeNewPilotBot>b__2_0 (System.Object obj) (at <3b4d42be961f435fb5284f443264fbc1>:0)
Scheduler.Update () (at <9411b2c55a4e44e68a95bd3ba148e05c>:0)
GameScheduler.Update () (at <9411b2c55a4e44e68a95bd3ba148e05c>:0)

Build: U42-510972-S

**Comment by ezonius** [comment]
Compiling the version from 6. June (a5d3a4a22d1b88c734931c7539d221f9c2b8ca5d), fixed the crash.

**Comment by CEG86** [comment]
Exact same issue.

NullReferenceException: Object reference not set to an instance of an object

Util.KInstantiate (UnityEngine.GameObject original, UnityEngine.Vector3 position, UnityEngine.Quaternion rotation, UnityEngine.GameObject parent, System.String name, System.Boolean initialize_id, System.Int32 gameLayer) (at <8c239b169b544cce8b8bc7ddd2d09e10>:0)
GameUtil.KInstantiate (UnityEngine.GameObject original, UnityEngine.Vector3 position, Grid+SceneLayer sceneLayer, UnityEngine.GameObject parent, System.String name, System.Int32 gameLayer) (at <9411b2c55a4e44e68a95bd3ba148e05c>:0)
GameUtil.KInstantiate (UnityEngine.GameObject original, UnityEngine.Vector3 position, Grid+SceneLayer sceneLayer, System.String name, System.Int32 gameLayer) (at <9411b2c55a4e44e68a95bd3ba148e05c>:0)
KnastoronOniMods.RocketControlStationNoChorePrecondition.<MakeNewPilotBot>b__2_0 (System.Object obj) (at <3b4d42be961f435fb5284f443264fbc1>:0)
Scheduler.Update () (at <9411b2c55a4e44e68a95bd3ba148e05c>:0)
GameScheduler.Update () (at <9411b2c55a4e44e68a95bd3ba148e05c>:0)

Build: U42-510972-S

**Comment by Sgt-Imalas** [comment]
I pushed an update that should fix this crash

**Comment by ezonius** [comment]
That fixed it for me, thanks
