### ISSUE TITLE
[ModTranslation] Chinese - CGM

### ISSUE THREAD

**Issue by Sgt-Imalas** [Sgt-Imalas/Sgt_Imalas-Oni-Mods#50]
### What mod is that translation for?

Cluster Generation Manager

### Additional Comments

translation template 1.3

### translation file

[clustertraitgenerationmanager_template.zip](https://github.com/Sgt-Imalas/Sgt_Imalas-Oni-Mods/files/11101114/clustertraitgenerationmanager_template.zip)

**Comment by LimA0LiN** [comment]
[clustertraitgenerationmanager_template_zh.zip](https://github.com/Sgt-Imalas/Sgt_Imalas-Oni-Mods/files/11102342/clustertraitgenerationmanager_template_zh.zip)

**Comment by Sgt-Imalas** [comment]
[clustertraitgenerationmanager_template.zip](https://github.com/Sgt-Imalas/Sgt_Imalas-Oni-Mods/files/11112482/clustertraitgenerationmanager_template.zip)
updated for 1.3.2

**Comment by Sgt-Imalas** [comment]
[ClusterTraitGenerationManager_dev.zip](https://github.com/Sgt-Imalas/Sgt_Imalas-Oni-Mods/files/11149932/ClusterTraitGenerationManager_dev.zip)
Pre-Release version 1.4, contains meteor season selector

**Comment by Sgt-Imalas** [comment]
[1.4clustertraitgenerationmanager_template.zip](https://github.com/Sgt-Imalas/Sgt_Imalas-Oni-Mods/files/11150428/1.4clustertraitgenerationmanager_template.zip)

**Comment by LimA0LiN** [comment]
![image](https://user-images.githubusercontent.com/32559936/232030547-c51d7997-6085-46e9-a5b1-41d0aae95b9d.png)
It seen that those words lack of translaction..?

**Comment by Sgt-Imalas** [comment]
these cannot be translated, since they do not have a name and no discerning modifiers, it simply uses their ID. 
you can hover on them for information of their content

**Comment by Sgt-Imalas** [comment]
[clustertraitgenerationmanager_template.zip](https://github.com/Sgt-Imalas/Sgt_Imalas-Oni-Mods/files/12233733/clustertraitgenerationmanager_template.zip)
I had to redo major parts of the UI, that has changed a lot of keys while also adding a few new strings
would you mind updating the translation?
