### ISSUE TITLE
[BUG]: crash

### ISSUE THREAD

**Issue by ranutdog** [Sgt-Imalas/Sgt_Imalas-Oni-Mods#51]
### Description of the bug/crash

KeyNotFoundException: The given key was not present in the dictionary.

System.Collections.Generic.Dictionary`2[TKey,TValue].get_Item (TKey key) (at <695d1cc93cca45069c528c15c9fdd749>:0)
CustomGameSettings.GetCurrentQualitySetting (System.String setting_id) (at <1f4c5a7d658c4522888fade7e74323ad>:0)
CustomGameSettings.GetCurrentQualitySetting (Klei.CustomSettings.SettingConfig setting) (at <1f4c5a7d658c4522888fade7e74323ad>:0)
CustomGameSettingsModifier.CustomSettingsController.LoadGameSettings () (at <2865be3a595b40158acd09676dd9beef>:0)
CustomGameSettingsModifier.CustomSettingsController.ShowWindow () (at <2865be3a595b40158acd09676dd9beef>:0)
CustomGameSettingsModifier.Patches.OnCustomMenuButtonPressed () (at <2865be3a595b40158acd09676dd9beef>:0)
KButtonMenu+<>c__DisplayClass11_1.<RefreshButtons>b__1 () (at <1f4c5a7d658c4522888fade7e74323ad>:0)
KButton.SignalClick (KKeyCode btn) (at <d35824e72985464e85149179dd14d71e>:0)
KButton.OnPointerClick (UnityEngine.EventSystems.PointerEventData eventData) (at <d35824e72985464e85149179dd14d71e>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IPointerClickHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at <e9635660f69b4d9d84c085aeda3be353>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) (at <e9635660f69b4d9d84c085aeda3be353>:0)
UnityEngine.EventSystems.EventSystem:Update()

Build: U46-552078-V

### Steps To Reproduce

I just downloaded this mod and opened the game menu in my archive. When I clicked on "Change difficulty", the game crashed

### Player.log

D:\w4play\steamapps\common\OxygenNotIncluded

**Comment by Sgt-Imalas** [comment]
not a log.
fixed in 1.0.1
