### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by charlotteanime47** [Sgt-Imalas/Sgt_Imalas-Oni-Mods#54]
### Description of the bug/crash

crash when have a meteor shower

### Steps To Reproduce

i don't know

### Player.log

[Player.log](https://github.com/Sgt-Imalas/Sgt_Imalas-Oni-Mods/files/11279770/Player.log)
too much Word github permit upload in word

**Comment by Sgt-Imalas** [comment]
crash is not related to any of my mods. 
you either had diseases expanded enabled previously or it is simply a base game crash

**Comment by charlotteanime47** [comment]
yeah you're right is crash from diseases expanded not turn on
