### ISSUE TITLE
[BUG]: CritterTraits Reborn, crash when loading map

### ISSUE THREAD

**Issue by margerber** [Sgt-Imalas/Sgt_Imalas-Oni-Mods#55]
### Description of the bug/crash

Upon loading a rather old savegame error message as shown in log. 
[ERROR] Hatch Error in Hatch.CritterTraits.OnPrefabInit
I hope its not a strange mod interaction.
Basegame ONI used. Modmanager used to ensure update to most recent version

EDIT: I fear a little bit more is wrong as the savegame is from early 2022, and having deactivated your mod, comes with a lot of other bugs.
EDITEDIT: Other bug was solely due to the new version of Ronivan's Chemical Processing.

### Steps To Reproduce

Loading map.

### Player.log

[Player.log](https://github.com/Sgt-Imalas/Sgt_Imalas-Oni-Mods/files/11315023/Player.log)

**Comment by Sgt-Imalas** [comment]
this crash looks a bit like an outdated version of the mod, can you get Mod Updater to force an update to the mod?

**Comment by margerber** [comment]
I did force update the mod using ONY's mod manager. I started a new game and it works just fine with it.
Loading the old maps (and I've tried a range of them) doesn't work though. I'll live without it, I guess
it's a local issue. :) Thanks.

**Comment by margerber** [comment]
Opened an almost pristine very old map. Saved it again, then added solely critter traits. It crashed again. Enough. :)

**Comment by Sgt-Imalas** [comment]
> I did force update the mod using ONY's mod manager. I started a new game and it works just fine with it. Loading the old maps (and I've tried a range of them) doesn't work though. I'll live without it, I guess it's a local issue. :) Thanks.

give it a try with mod updater, ony mod manager is **very** buggy about the updating

**Comment by margerber** [comment]
Retried with the mod updater by Stephen. Same result.
