### ISSUE TITLE
[Possible BUG]: Can it be that a change in the meteor difficulty interfers with Trailblazer landing

### ISSUE THREAD

**Issue by pixelkritzel** [Sgt-Imalas/Sgt_Imalas-Oni-Mods#56]
### Description of the bug/crash

after changing the meteor difficulty from doomsday to clear skies I can't land trailblazers anymore. Is there a possibility of overlapping code? I know it's a long shot.

### Steps To Reproduce

just the question

### Player.log

It's an empty file
[player..log](https://github.com/Sgt-Imalas/Sgt_Imalas-Oni-Mods/files/11375728/player.log)

**Comment by Sgt-Imalas** [comment]
No

**Comment by pixelkritzel** [comment]
Thanks
