### ISSUE TITLE
[BUG]: Disconnecting docking tubes crashes the game

### ISSUE THREAD

**Issue by crazymachinefan** [Sgt-Imalas/Sgt_Imalas-Oni-Mods#59]
### Description of the bug/crash

What the title says. I was checking if docking tubes transferred power across them in a test world and the game exploded. Here's the error report:

NullReferenceException: Object reference not set to an instance of an object

Rockets_TinyYetBig.Behaviours.DockingManager.Sim1000ms (System.Single dt) (at <a07729bb93894443a1763821640e04c7>:0)
SimAndRenderScheduler+Sim1000msUpdater.Update (ISim1000ms updater, System.Single dt) (at <0f4b778ef79c497e89f6ee18303840cf>:0)
UpdateBucketWithUpdater`1[DataType].Update (System.Single dt) (at <0f4b778ef79c497e89f6ee18303840cf>:0)
StateMachineUpdater+BucketGroup.AdvanceOneSubTick (System.Single dt) (at <0f4b778ef79c497e89f6ee18303840cf>:0)
StateMachineUpdater.AdvanceOneSimSubTick () (at <0f4b778ef79c497e89f6ee18303840cf>:0)
Game.SimEveryTick (System.Single dt) (at <990b4cf9a7d84305ad7eaef1059b672b>:0)
Game.Update () (at <990b4cf9a7d84305ad7eaef1059b672b>:0)

Build: U47-561558-SD

### Steps To Reproduce

1. Build two rockets
2. Add docking tubes
3. Launch both into space and connect them
4. Disconnect
5. Game explodes

### Player.log

Quick note: I've taken steps to obfuscate some personal information. It shouldn't affect the important stuff.

[Player.log](https://github.com/Sgt-Imalas/Sgt_Imalas-Oni-Mods/files/11765526/Player.log)

**Comment by Sgt-Imalas** [comment]
thx for the report, fixed in 2.6.3
