### ISSUE TITLE
[BUG]: Rocketry Expanded crash on coal module build

### ISSUE THREAD

**Issue by GScully** [Sgt-Imalas/Sgt_Imalas-Oni-Mods#60]
### Description of the bug/crash

While building the coal generator out of niobium the game crashed,
NullReferenceException: Object reference not set to an instance of an object

Rockets_TinyYetBig.Behaviours.RTB_ModuleGenerator.IsProducingPower () (at <e3d2fa547e0c407e901fb13fa5cbed8e>:0)
Rockets_TinyYetBig.Patches.StatusItemsPatches+OptimizedRewriteForInfoPanel.Prefix (RocketSimpleInfoPanel __instance, CollapsibleDetailContentPanel rocketStatusContainer, UnityEngine.GameObject selectedTarget) (at <e3d2fa547e0c407e901fb13fa5cbed8e>:0)
(wrapper dynamic-method) RocketSimpleInfoPanel.RocketSimpleInfoPanel.Refresh_Patch1(RocketSimpleInfoPanel,CollapsibleDetailContentPanel,UnityEngine.GameObject)
SimpleInfoScreen.Refresh (System.Boolean force) (at <990b4cf9a7d84305ad7eaef1059b672b>:0)
SimpleInfoScreen.Update () (at <990b4cf9a7d84305ad7eaef1059b672b>:0)

Build: U47-561558-SD

### Steps To Reproduce

build rocket, add coal power engine made from niobium, on completion the game crashes.

### Player.log

[Player.log](https://github.com/Sgt-Imalas/Sgt_Imalas-Oni-Mods/files/11779728/Player.log)

**Comment by Sgt-Imalas** [comment]
log does not contain a crash, please attach a log that contains a crash

**Comment by GScully** [comment]
I guess the bug can be closed I could not reproduce it.

**Comment by Sgt-Imalas** [comment]
Ill monitor the thing
