### ISSUE TITLE
[BUG]: POI sensor listed first in build menu, lacks subcategory

### ISSUE THREAD

**Issue by llunak** [Sgt-Imalas/Sgt_Imalas-Oni-Mods#64]
### Description of the bug/crash

The POI sensor building from Rocketry Expanded mod is listed as very first in the "Automation" build menu.

The call to AddBuildingToPlanScreen() for it needs "sensors" as the 3rd parameter.

### Steps To Reproduce

- Click 'Automation' build icon at the bottom, see where the sensor building is.

### Player.log

N/A

**Comment by Sgt-Imalas** [comment]
thx for the report, fixed in next update
