### ISSUE TITLE
[BUG]: Game crashes on custom skills selected print

### ISSUE THREAD

**Issue by Yaksinikos** [Sgt-Imalas/Sgt_Imalas-Oni-Mods#65]
### Description of the bug/crash

Sometimes when I click on the ready to print - printing pod the game freezes and than crashes after 10 minutes.
Sometimes I can enter the printing menu and select a dupe, so, when editing the skills of a dupe, the game crashes on "print"-confirmation.

### Steps To Reproduce

1. Wait till print is ready
2. select a dupe
3. select some skills
4. print

### Player.log

[Player-prev.log](https://github.com/Sgt-Imalas/Sgt_Imalas-Oni-Mods/files/11926718/Player-prev.log)
[mods.json](https://github.com/Sgt-Imalas/Sgt_Imalas-Oni-Mods/files/11926747/mods.txt)

**Comment by Sgt-Imalas** [comment]
verstion 5.0.9 has been released, there I added a prevention check for the crash in the log and added explicit compatibility with always3interests
