### ISSUE TITLE
[ModTranslation]: Drywall Colours

### ISSUE THREAD

**Issue by DarkEviL88** [Sgt-Imalas/Sgt_Imalas-Oni-Mods#66]
### What mod is that translation for?

Drywall Colours

### Additional Comments

The mod works, but when you turn it on the localization of the game (non-mod) drywall becomes in English. Drywall from the mod, I have already translated into Russian, now playing look how best to localize, in English all the blue drywall called H2O, and in the Russian localization says water, yes it is one and the same, but... I can make mistakes in texts, because the inspiration to do something comes to me when I am sleepy. I also translated your AI controlled rockets, I am testing how it is in the game and whether I have made mistakes, not everywhere the text is translated, there are places where there is English

### translation file

[ru.zip](https://github.com/Sgt-Imalas/Sgt_Imalas-Oni-Mods/files/11979173/ru.zip)

**Comment by DarkEviL88** [comment]
As it turned out this mod changes the language of all the decor, the base object has a name in the selected language, but its other skins are all in English and this applies to drywall, lamps, beds, flower pots and so on.
![image](https://github.com/Sgt-Imalas/Sgt_Imalas-Oni-Mods/assets/50534207/bf3630c9-fbaf-47f7-a619-25454f1a0ab5)
![image](https://github.com/Sgt-Imalas/Sgt_Imalas-Oni-Mods/assets/50534207/acf424cb-d08d-4bf0-a216-5d9ac8cd02ae)

**Comment by Sgt-Imalas** [comment]
thx for the notice.
I have fixed the bug and added your translations
