### ISSUE TITLE
[ModTranslation]: Mineralizer Reborn

### ISSUE THREAD

**Issue by DarkEviL88** [Sgt-Imalas/Sgt_Imalas-Oni-Mods#67]
### What mod is that translation for?

Mineralizer Reborn

### Additional Comments

It's just a translation.

### translation file

[ru.zip](https://github.com/Sgt-Imalas/Sgt_Imalas-Oni-Mods/files/12023947/ru.zip)

**Comment by Sgt-Imalas** [comment]
added
