### ISSUE TITLE
[BUG]: Drywall Colours localization

### ISSUE THREAD

**Issue by DarkEviL88** [Sgt-Imalas/Sgt_Imalas-Oni-Mods#68]
### Description of the bug/crash

Thank you for updating the mod, now the game objects are all good with localization, but your mod stopped working localization, I tried changing the language type in the .po file from ru_RU to ru (helps with some mods) and it did not help. I tried unsubscribing from the mod restart the game subscribe to the mod and restart the game again and this also did not help.

### Steps To Reproduce

-

### Player.log

[Player.log](https://github.com/Sgt-Imalas/Sgt_Imalas-Oni-Mods/files/12024502/Player.log)

**Comment by Sgt-Imalas** [comment]
Ah I renamed some internal strings and forgot to include these changes in the po file.Will fix later

**Comment by DarkEviL88** [comment]
Then I will correct the translation, after your fix.

**Comment by DarkEviL88** [comment]
It's just that I was doing a translation based on your text almost directly, and now the names of the drywall are different. H2O is now bubbles and Charcoal is now cobblestone and so on, I think the translation should be corrected too. Too bad I don't know much about textures, just have a couple ideas for additional drywall. The drywall for the lab is snowy white with flasks for chemical experiments. Or wallpaper for the bedroom with some animal from the game itself (like pips) and a soft color.

**Comment by Sgt-Imalas** [comment]
I see.
If you want such motives for yourself, the wonderfull mod ["Backwalls"](https://steamcommunity.com/sharedfiles/filedetails/?id=2921809973) by Aki has a feature that allows you to add your own motives as additional backwall skins.
(note: not drywall, the backwall building from that mod)
these boil down to being a 128x128px png and an optional metadata json file and creating is "just" drawing them

**Comment by DarkEviL88** [comment]
Thanks.

**Comment by DarkEviL88** [comment]
Backwalls mod has terrible borders like tiles, I want to see borders like drywall, I wrote to the author of the mod, as the mod does not fully work localization, and about the borders. I wish there was a similar mod for drywall that would just add new custom textures to the drywall listing.

**Comment by DarkEviL88** [comment]
It turns out you've already updated both the template and the mod, and I somehow missed it while I was solving my problems.
[ru.zip](https://github.com/Sgt-Imalas/Sgt_Imalas-Oni-Mods/files/12345368/ru.zip)
The ice block statues remained in English, but it's not because of your mod, if my memory serves me right, it was like that without mods.
![image](https://github.com/Sgt-Imalas/Sgt_Imalas-Oni-Mods/assets/50534207/77eb7b89-71b3-4bb0-8308-4c984564af93)

**Comment by DarkEviL88** [comment]
Sorry for the off-topic message, I installed the mods of one author, on sealed boxes, trash cans and first aid kits, the mods have a skin system, but it breaks the localization of statues and drywall, the author of the mods does not know what the reason is, can you suggest what could be the reason? His 3 mods do not affect the original game objects. Unfortunately the author of these mods did not share the source code.

**Comment by Sgt-Imalas** [comment]
that mod author patches wrong.
skin patches have to happen after localisation

**Comment by Sgt-Imalas** [comment]
strings fixed
