### ISSUE TITLE
Issue with Mod "Rocketry Expanded"

### ISSUE THREAD

**Issue by Saftii** [Sgt-Imalas/Sgt_Imalas-Oni-Mods#7]
I wanted to report, that I can't connect Liquid Pipes to the Liquid Spacefarer Output/Input Port inside the 
1. Extended Solo Spacefarer Nosecone (provided by Mod)
2. Solo Spacefarer Nosecone (provided by Game)
3. Spacefarer Module  (provided by Game)
Gas Pipes are all fine, as well as Liquid Pipes inside Extended Spacefarer and Stargazer Modul
![20220722112132_1](https://user-images.githubusercontent.com/97677265/180408465-3e35a4ed-78fc-4f7e-849e-5d004f52be21.jpg)
![20220722112139_1](https://user-images.githubusercontent.com/97677265/180408472-0fa4969e-9f41-44b6-a8d5-54abb313cee3.jpg)
![20220722112147_1](https://user-images.githubusercontent.com/97677265/180408476-97f31f6a-3c32-4a93-8149-72bc4c22c61d.jpg)
Hopefully these Pictures help to understand what I mean. Also tested with all other Mods turned off and inside different worlds.
Have a great Day.
~Saftii

**Comment by Sgt-Imalas** [comment]
Fix in version 1.0.2 (applies only to newly constructed rockets)
