### ISSUE TITLE
[BUG]: Can't select metalic swampy as teleport destination

### ISSUE THREAD

**Issue by guildcrest** [Sgt-Imalas/Sgt_Imalas-Oni-Mods#75]
### Description of the bug/crash

When creating a cluster with Cluster Generation Manager the metallic swampy asteroid is not available as a teleport destination for any starting asteroid. Checked with all other mods mods except Mod Updater and CGM disabled and verified integrity of game files

### Steps To Reproduce

1. Start a new game with the spaced out dlc active
2. Select 'survival' as the mode
3. Pick any starting asteroid and open CGM
4. Go to teleport asteroid in the left hand column
5. Notice that the number of asteroids is not the same between Starter and Teleport and that Metallic Swampy is not listed

### Player.log

[Player.log](https://github.com/Sgt-Imalas/Sgt_Imalas-Oni-Mods/files/12336182/Player.log)

**Comment by Sgt-Imalas** [comment]
Good find!

it is not on the list as there is no vanilla cluster that uses a teleporter metallic swampy, even tho the file for it exists.
I will fix this next update

**Comment by Sgt-Imalas** [comment]
Fixed with release 2.1
