### ISSUE TITLE
one more issue: NullReferenceException: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by Artorin** [Sgt-Imalas/Sgt_Imalas-Oni-Mods#8]
It immediately crashs if AI modul was сonstructed
[Player.log](https://github.com/Sgt-Imalas/Sgt_Imalas-Oni-Mods/files/9184705/Player.log)

**Comment by Artorin** [comment]
AI Controlled Rockets DLC, another mods were off :)

**Comment by Artorin** [comment]
seems to be fixed on AI Controlled Rockets: Game crash after recent update #5 but still something goes wrong

**Comment by Sgt-Imalas** [comment]
the crash came from an malfunctioning update, the latest version does not have this bug
