### ISSUE TITLE
[BUG]: AI Controlled Rockets - Can't launch due to obstructed launch path

### ISSUE THREAD

**Issue by GamerRy123** [Sgt-Imalas/Sgt_Imalas-Oni-Mods#80]
### Which Mod?

AI Controlled Rockets (DLC)

### Description of the bug/crash

What happened - Rocket cannot launch due to obstructed launch path despite the launch path being clear

What should happen - Rocket can launch

Potential cause - Rocket seems to not like the AI brain module as that seems to be obstructing it
https://imgur.com/a/5LEi3SO

### Steps To Reproduce

Build rocket with ai brain module

### Player.log

No crash just rocket will not launch

**Comment by Sgt-Imalas** [comment]
nice find

those two mesh tiles are blocking it 
![grafik](https://github.com/Sgt-Imalas/Sgt_Imalas-Oni-Mods/assets/20609939/0b7b2650-5bb7-4dcc-a0d0-909091ea2083)
(since I forgot to update that check from when the module was only 3 wide.)
will be fixed next update

**Comment by GamerRy123** [comment]
sorry to message on a closed thread but do you have a rough time for when the update will be out? just wanna know if I should wait for it or switch to dupe rockets since I get that with mods its just a "its out when its out" kinda thing so if you don't then its fine

**Comment by Sgt-Imalas** [comment]
today
