### ISSUE TITLE
[BUG]: Scan and Relay Satellites Mission Control Bug

### ISSUE THREAD

**Issue by Dan-Fries** [Sgt-Imalas/Sgt_Imalas-Oni-Mods#84]
### Which Mod?

Scan & Relay Satelites

### Description of the bug/crash

The mission control station extend functionality appears to be broken, the dupes will get an errand calling them to the station for a research task but they never get a progress bar and the rocket never gets the boost. They are repeatedly called for this errand and essentially just end up idling in front of the mission control station. I have tried replacing the satellites in several different locations and rebuilding the mission control station but the same behavior persists. Looking at the log it is repeatedly trying to add a satelite node every several ticks which is probably where this is failing, I am running quite a few mods so there definitely could be a conflict.

### Steps To Reproduce

Place Satellite and mission control station, fly rocket within range of satellite

### Player.log

[Player.log](https://github.com/Sgt-Imalas/Sgt_Imalas-Oni-Mods/files/13259891/Player.log)

**Comment by Sgt-Imalas** [comment]
thx for the report, there was an additional range check in the workable I missed, causing the worker task to become invalid

fixed in 1.2.3
