### ISSUE TITLE
[BUG]: Crash in Rocketry Expanded (DLC) after October 2023 update

### ISSUE THREAD

**Issue by aantono** [Sgt-Imalas/Sgt_Imalas-Oni-Mods#85]
### Which Mod?

Rocketry Expanded (DLC)

### Description of the bug/crash

Game crashes when Rocketry Expanded (DLC) is enabled

### Steps To Reproduce

Start  the game, enable Rocketry Expanded (DLC), game crashes.

### Player.log

[Player.log](https://github.com/Sgt-Imalas/Sgt_Imalas-Oni-Mods/files/13261187/Player.log)

**Comment by Sgt-Imalas** [comment]
Update your mod, its outdated
use the force update feature of mod updater for that
