### ISSUE TITLE
[BUG]: After update for Duplicant Stat Selector 6.1.1 

### ISSUE THREAD

**Issue by jefkin** [Sgt-Imalas/Sgt_Imalas-Oni-Mods#89]
### Which Mod?

 Duplicant Stat Selector

### Description of the bug/crash

After updating it failed on the first use, checking the comments section of the mod, discovered that the mod added Mod Updater, installed that and tried again with the same results.  Waited a few days to see if there were any more later updates.  Then went back to the comments and tried the processes detailed by Sgt_Imalas with the same results.

Attached is my latest Player.log

### Steps To Reproduce

Start the game click on any of the buttons in the colony printer.  (I tried all of them they all failed).

### Player.log

[Player.log](https://github.com/Sgt-Imalas/Sgt_Imalas-Oni-Mods/files/13512922/Player.log)

**Comment by jefkin** [comment]
DSS seems to be enabled during startup.  I tried again and got a duplicate log.  So I looked into the log file a bit deeper, turns out I'm getting logs and notices about a lot of mods that I thought were uninstalled, but apparently have remanent ## files in my file system.  I will clean them out after work and have a go again, in case this is a case of musical chairs and the problem isn't your stuff...

**Comment by Sgt-Imalas** [comment]
Update: Something is wrong with the linux asset bundle, thats whats causing the crash on clicking the buttons

**Comment by Sgt-Imalas** [comment]
I have updated the steam version to 6.1.3 with fixed asset bundles
due to the fact that 6.1.2 didnt copy the file properly, I had to do a second update, this will likely confuse the mod update, so you might need mod updater force update.
you know when the right version is installed if the version number inside of the config says 6.1.3 (the number on the mod list entry can be lying)

**Comment by jefkin** [comment]
Excellent, this solved the usability issue, just added a duplicant using the mod controls.  Thanks, I'll close
