### ISSUE TITLE
Bug report: duplicants got stuck construction digging vacuum in Rocketry Expanded

### ISSUE THREAD

**Issue by AlbertNewton** [Sgt-Imalas/Sgt_Imalas-Oni-Mods#9]
I built a Stargazer nosecone and started building things in it, but three tiles from the right was a vertical line of tiles where any time I tried to build something the duplicants got stuck construction digging the vacuum.
Saving and reloading fixed the problem; I didn't think at the time to take a save while the duplicants were digging.
I installed the Rocketry Expanded mod after I started the world, but before I made any rockets.
I do have a lot of other mods installed, but none that affect how the world grid is allocated.

Attached is a save file from a few cycles later, and all the autosaves I could find.
[Save game.zip](https://github.com/Sgt-Imalas/Sgt_Imalas-Oni-Mods/files/9299756/Save.game.zip)

**Comment by Sgt-Imalas** [comment]
thx for the save, It seems to have been neutronium that got removed in the sim, but not in the game grid itself. That way, reloading fixed it
