### ISSUE TITLE
[BUG]: Crash when swapping modules.

### ISSUE THREAD

**Issue by faltonico** [Sgt-Imalas/Sgt_Imalas-Oni-Mods#91]
### Which Mod?

Scan & Relay Satellites (DLC)

### Description of the bug/crash

I tried swapping a satellite module for a cargo one after the rocket returned from deploying it. And it crashed:

NullReferenceException

UnityEngine.Component.GetComponent[T] () (at <72b60a3dd8cd4f12a155b761a1af9144>:0)
KMonoBehaviour.IStateMachineTarget.GetComponent[ComponentType] () (at <7609d690302f4d1693caa0c1a81ea5cb>:0)
StateMachine+Instance.GetComponent[ComponentType] () (at <ddc0d36b5a284ddbbbfebcd9d8d8f4ca>:0)
LogicSatellites.Behaviours.SatelliteCarrierModule+StatesInstance.IsEntityAtLocation () (at <5f62bdf41f74432db75138e16303be62>:0)
LogicSatellites.Behaviours.SatelliteCarrierModule+StatesInstance.CanRetrieveSatellite () (at <5f62bdf41f74432db75138e16303be62>:0)
LogicSatellites.Behaviours.SatelliteCarrierModuleSideScreen.RefreshStrings () (at <5f62bdf41f74432db75138e16303be62>:0)
LogicSatellites.Behaviours.SatelliteCarrierModuleSideScreen.OnShow (System.Boolean show) (at <5f62bdf41f74432db75138e16303be62>:0)
KScreen.Show (System.Boolean show) (at <7609d690302f4d1693caa0c1a81ea5cb>:0)
DetailsScreen+<>c.<DeactivateSideContent>b__47_0 (DetailsScreen+SideScreenRef scn) (at <ddc0d36b5a284ddbbbfebcd9d8d8f4ca>:0)
System.Collections.Generic.List`1[T].ForEach (System.Action`1[T] action) (at <695d1cc93cca45069c528c15c9fdd749>:0)
DetailsScreen.DeactivateSideContent () (at <ddc0d36b5a284ddbbbfebcd9d8d8f4ca>:0)
DetailsScreen.OnCmpDisable () (at <ddc0d36b5a284ddbbbfebcd9d8d8f4ca>:0)
KMonoBehaviour.OnDisable () (at <7609d690302f4d1693caa0c1a81ea5cb>:0)
UnityEngine.GameObject:SetActive(Boolean)
RootMenu:CloseSubMenus()
RootMenu:OnSelectObject(Object)
EventSystem:Trigger(GameObject, Int32, Object)
KMonoBehaviour:Trigger(Int32, Object)
SelectTool:SelectTool.Select_Patch1(SelectTool, KSelectable, Boolean)
DetailsScreen:DetailsScreen.DeselectAndClose_Patch1(DetailsScreen)
DetailsScreen:OnKeyUp(KButtonEvent)
KScreenManager:OnKeyUp(KButtonEvent)
KInputHandler:HandleKeyUp(KButtonEvent)
KInputHandler:HandleKeyUp(KButtonEvent)
KInputHandler:HandleEvent(KInputEvent)
KInputController:Dispatch()
KInputManager:Dispatch()
KInputManager:Update()
GameInputManager:Update()
Global:Global.Update_Patch1(Global)

Build: U50-583750-SD

### Steps To Reproduce

I haven't reproduce it yet.

### Player.log

[Player - Copy.log](https://github.com/Sgt-Imalas/Sgt_Imalas-Oni-Mods/files/13667395/Player.-.Copy.log)

**Comment by Sgt-Imalas** [comment]
Couldnt reproduce, I pushed update 1.2.6, this should fix it
