### ISSUE TITLE
[ModTranslation]: Utility Glass

### ISSUE THREAD

**Issue by DarkEviL88** [Sgt-Imalas/Sgt_Imalas-Oni-Mods#98]
### What mod is that translation for?

Not listed (use textfield below)

### Additional Comments

Russian translation. You wrote "Transparent Aluminum" in the description field for Reinforced Window Tile, but the recipe uses steel, so I translated as "Transparent Steel". Maybe I'm misunderstanding something.

### translation file

[ru.zip](https://github.com/Sgt-Imalas/Sgt_Imalas-Oni-Mods/files/14273701/ru.zip)

**Comment by Sgt-Imalas** [comment]
its a reference to star trek IV

**Comment by DarkEviL88** [comment]
I don't know whether to take your reference back or leave it as is. If someone who speaks Russian downloads the mod, they may not understand this reference, but "transparent steel" sounds strange too:)

**Comment by DarkEviL88** [comment]
If you want to keep the reference, then "Transparent Aluminum" would be "Прозрачный алюминий" in Russian.

**Comment by Sgt-Imalas** [comment]
added with release 1.1.1
